### ISSUE TITLE
Kde a jak pomoct

### ISSUE THREAD

**Issue by zbycz** [osmcz/osmcz#89]
Zde jsou úkoly vhodné jako jednorázovky pro kohokoliv z komunity, kdo by se rád zapojil do vývoje. 
- Pokud v úkolu něco není popsané, pište. 
- Pro vývoj stačí vcelku základní znalosti Javascriptu či CSS. 
- Github: Ideální forma je udělat si "Fork" tlačítkem nahoře, což zkopíruje projekt do vašeho profilu, kde je možné provádět zápisové změny - k editaci souborů na vlastním PC poslouží [desktop.github.com](https://desktop.github.com/) (pro menší úpravy jen :pencil2: vpravo nad každým souborem). Po vyhotovení změn a provedení commitu do forku, stačí poslat komentář s odkazem. Kdo umí, tak pull-request.

Seřazeno od cca snazších:
- [x] Upravený attribution control #56
- [ ] Přidat 3D vrstvu z osmbuildings #51
- [ ] Kreslitko do mapy #50
- [x] Vrstva s fixme a note #53
- [ ] Nástroj pro měření vzdálenosti #8
- [ ] Přidat mapillary street-view #16
- [ ] Noční řežim #48 (blbůstka, serverová záležitost)
- [ ] **Poladit výkon** ve Vrstvě aktivních POI #4

![image](https://cloud.githubusercontent.com/assets/385047/12882309/008b4d02-ce51-11e5-8c97-bd9ef8bf1d9f.png)

**Comment by walley** [comment]
bude uz nejaky ten toolbar a panel apod? 
bez toho note, kreslitko a dalsi blbosti neni jak ovladat. 
nebo jak to udelat bez toho? kde budou aktivacni cudliky?

**Comment by zbycz** [comment]
Toolbar bych v zásadě ani neplánoval, všecko by mělo jít rozložit po obrazovce tak, aby to dávalo smysl (přidal jsem nahoru wireframe). Jestli něco chybí, řekni, doplnil bych to do obrázku.

Panel už je připravený v css, vlastně ho můžeš začít používat - stačí odkomentovat a zavolat `$('#map-sidebar').html('obsah').show()` resp `.toggle()`. Chci tam ještě nějakou globální obsluhu, ale to stačí až později.

**Comment by walley** [comment]
jo super.
sem si vsiml ze to tam lezi zapoznamkovany:)

**Comment by severak** [comment]
@zbycz Kde přesně je ten wireframe?

**Comment by zbycz** [comment]
ouch, přidal jsem ho, ale neuložil :-) tak druhý pokus - je nahoře v tomto issue.

**Comment by severak** [comment]
Napsal jsem návrh na optimalizaci aktivní vrstvy - viz #100.
